const replacementRules = {
    "ALPHA": 'A',
    "BRAVO": 'B',
    "CHARLIE": 'C',
    "DELTA": 'D',
    "ECHO": 'E',
    "FOXTROT": 'F',
    "GOLF": 'G',
    "HOTEL": 'H',
    "INDIA": 'I',
    "JULIET": 'J',
    "KILO": 'K',
    "LIMA": 'L',
    "MIKE": 'M',
    "NOVEMBER": 'N',
    "OSCAR": 'O',
    "PAPA": 'P',
    "QUEBEC": 'Q',
    "ROMEO": 'R',
    "SIERRA": 'S',
    "TANGO": 'T',
    "UNIFORM": 'U',
    "VICTOR": 'V',
    "WHISKEY": 'W',
    "XRAY": 'X',
    "YANKEE": 'Y',
    "ZULU": 'Z',
    [`(THIS IS HELSINKI-VANTAA ARRIVAL AND DEPARTURE INFORMATION) (\\w)`]: "EFHK ARR AND DEP INFO $2",
    [`(THIS IS HELSINKI-VANTAA)`]: "EFHK",
    [`(ARRIVAL INFORMATION) (\\w)`]: "ARR INFO $2",
    [`(DEPARTURE INFORMATION) (\\w)`]: "DEP INFO $2",
    [`AT TIME (\\d{4})`]: '$1',
    "APPROACH": 'APCH',
    "ARRIVAL": 'ARR',
    "DEPARTURE": 'DEP',
    "RUNWAY": 'RWY',
    "RUNWAYS": 'RWYS',
    "DEP RWY 22L AND 22R": 'DEP RWYS 22R AND 22L',
    "DEP RWY 04R AND 15": 'DEP RWYS 04R AND 15',
    "ARR RWY 04L AND 04R": 'ARR RWYS 04L AND 04R',
    "ARR RWY 22L AND 22R": 'ARR RWYS 22L AND 22R',
    "CLEAR AND DRY": '',
    "TRANSITION LEVEL (\\d{2})": 'TRL $1',
    "DEGREES": 'DEG',
    "KNOTS": 'KT',
    "MAXIMUM": 'MAX',
    "TEMPERATURE": 'T',
    "TMP ": 'T ',
    "DEW POINT": 'DP',
    "QNH (\\d{4})": 'QNH $1',
    "ADVISE ON INITIAL CONTACT YOU HAVE INFORMATION": 'ACK INFO',
    "VERTICAL VISIBILITY": 'VV',
    "VISIBILITY": 'VIS',
    "CAVOK": 'CAVOK',
    "BROKEN": 'BKN',
    "SCATTERED": 'SCT',
    "OVERCAST": 'OVC',
    "FEW": 'FEW',
    "PROBABILITY": 'PROB',
    "LIGHT": 'FBL',
    "HEAVY": 'HVY',
    "MODERATE": 'MOD',
    "CUMULONIMBUS": 'CB',
    "MOVING": 'MOV',
    "EAST": 'E',
    "NORTH": 'N',
    "WEST": 'W',
    "SOUTH": 'S',
    "NORTHWEST": 'NW',
    "SOUTHWEST": 'SW',
    "NORTHEAST": 'NE',
    "SOUTHEAST": 'SE',
    "ABOVE": 'ABV',
    "FORECASTED": 'FCST',
    "FLIGHT LEVEL": 'FL',
    "NO SIGNIFICANT CLOUDS": 'NSC',
    "SEVERE": 'SEV',
    "CLEAR SKY": 'SKC',
    "TEMPORARY": 'TEMPO',
    "WIND SHEAR": 'WS',
    "REPORTED": 'REP',
    "BETWEEN": 'BTN',
    "FROM": 'FM',
    "FREEZING": 'FZ',
    "ICING": 'ICE',
    "NO CLOUDS DETECTED": 'NCD',
    "RUNWAY VISUAL RANGE": 'RVR',
    "TOWERING CUMULUS": 'TCU',
    "VARIABLE": 'VRB',
    "GUSTING": 'MAX',
    "GUST": 'MAX',
    "GUSTS": 'MAX',
    " SHALLOW": ' MI',
    " PARTIAL": ' PR',
    " PATCHES": ' BC',
    " LOW DRIFTING": ' DR',
    " BLOWING": ' BL',
    " SHOWERS": ' SH',
    " THUNDERSTORM": ' TS',
    "DRIZZLE ": 'DZ ',
    "RAIN ": 'RA ',
    "SNOW GRAINS ": 'SG ',
    "SNOW ": 'SN ',
    "ICE CRYSTALS ": 'IC ',
    "ICE PELLETS ": 'PL ',
    "SMALL HAIL ": 'GS ',
    "HAIL ": 'GR ',
    "MIST ": 'BR ',
    "FOG ": 'FG ',
    "WIDESPREAD DUST ": 'DU ',
    "KILOMETERS": 'KM',
    "METERS": 'M',
    "VICINITY": 'VC',
    "FEET": 'FT',
    "NOSIG": 'NOSIG',
    "BECOMING": 'BECMG'
  };
  
  const replacementRulesOld = {
    "ALPHA": 'A',
    "BRAVO": 'B',
    "CHARLIE": 'C',
    "DELTA": 'D',
    "ECHO": 'E',
    "FOXTROT": 'F',
    "GOLF": 'G',
    "HOTEL": 'H',
    "INDIA": 'I',
    "JULIET": 'J',
    "KILO": 'K',
    "LIMA": 'L',
    "MIKE": 'M',
    "NOVEMBER": 'N',
    "OSCAR": 'O',
    "PAPA": 'P',
    "QUEBEC": 'Q',
    "ROMEO": 'R',
    "SIERRA": 'S',
    "TANGO": 'T',
    "UNIFORM": 'U',
    "VICTOR": 'V',
    "WHISKEY": 'W',
    "XRAY": 'X',
    "YANKEE": 'Y',
    "ZULU": 'Z',
    [`(THIS IS HELSINKI-VANTAA ARRIVAL AND DEPARTURE INFORMATION) (\\w)`]: "EFHK ARR AND DEP INFO $2<br/>",
    [`(THIS IS HELSINKI-VANTAA)`]: "EFHK",
    [`(ARRIVAL INFORMATION) (\\w)`]: "ARR INFO $2<br/>",
    [`(DEPARTURE INFORMATION) (\\w)`]: "DEP INFO $2<br/>",
    [`AT TIME (\\d{4})`]: '$1<br/>',
    "APPROACH": 'APCH',
    "ARRIVAL": '<br/>ARR',
    "DEPARTURE": '<br/>DEP',
    "RUNWAY": 'RWY',
    "RUNWAYS": 'RWYS',
    "DEP RWY 22L AND 22R": 'DEP RWYS 22R AND 22L',
    "ARR RWY 04L AND 04R": 'ARR RWYS 04L AND 04R',
    "ARR RWY 22L AND 22R": 'ARR RWYS 22L AND 22R',
    "CLEAR AND DRY": '',
    "TRANSITION LEVEL (\\d{2})": '<br/>TRL $1<br/>',
    "DEGREES": 'DEG',
    "KNOTS": 'KT',
    "MAXIMUM": 'MAX',
    "TEMPERATURE": '<br/>T',
    "TMP ": 'T ',
    "DEW POINT": 'DP',
    "QNH (\\d{4})": 'QNH $1<br/>',
    "ADVISE ON INITIAL CONTACT YOU HAVE INFORMATION": '<br/>ACK INFO',
    "VERTICAL VISIBILITY": '<br/>VV',
    "VISIBILITY": '<br/>VIS',
    "CAVOK": '<br/>CAVOK',
    "BROKEN": '<br/>BKN',
    "SCATTERED": '<br/>SCT',
    "OVERCAST": '<br/>OVC',
    "FEW": '<br/>FEW',
    "PROBABILITY": 'PROB',
    "LIGHT": 'FBL',
    "HEAVY": 'HVY',
    "MODERATE": 'MOD',
    "CUMULONIMBUS": 'CB',
    "MOVING": 'MOV',
    "EAST": 'E',
    "NORTH": 'N',
    "WEST": 'W',
    "SOUTH": 'S',
    "NORTHWEST": 'NW',
    "SOUTHWEST": 'SW',
    "NORTHEAST": 'NE',
    "SOUTHEAST": 'SE',
    "ABOVE": 'ABV',
    "FORECASTED": 'FCST',
    "FLIGHT LEVEL": 'FL',
    "NO SIGNIFICANT CLOUDS": 'NSC',
    "SEVERE": 'SEV',
    "CLEAR SKY": 'SKC',
    "TEMPORARY": 'TEMPO',
    "WIND SHEAR": 'WS',
    "REPORTED": 'REP',
    "BETWEEN": 'BTN',
    "FROM": 'FM',
    "FREEZING": 'FZ',
    "ICING": 'ICE',
    "NO CLOUDS DETECTED": 'NCD',
    "RUNWAY VISUAL RANGE": 'RVR',
    "TOWERING CUMULUS": 'TCU',
    "VARIABLE": 'VRB',
    "GUSTING": 'MAX',
    "GUST": 'MAX',
    "GUSTS": 'MAX',
    " SHALLOW": ' MI',
    " PARTIAL": ' PR',
    " PATCHES": ' BC',
    " LOW DRIFTING": ' DR',
    " BLOWING": ' BL',
    " SHOWERS": ' SH',
    " THUNDERSTORM": ' TS',
    "DRIZZLE ": 'DZ ',
    "RAIN ": 'RA ',
    "SNOW GRAINS ": 'SG ',
    "SNOW ": 'SN ',
    "ICE CRYSTALS ": 'IC ',
    "ICE PELLETS ": 'PL ',
    "SMALL HAIL ": 'GS ',
    "HAIL ": 'GR ',
    "MIST ": 'BR ',
    "FOG ": 'FG ',
    "WIDESPREAD DUST ": 'DU ',
    "KILOMETERS": 'KM',
    "METERS": 'M',
    "VICINITY": 'VC',
    "FEET": 'FT',
    "NOSIG": 'NOSIG',
    "BECOMING": 'BECMG'
  };

  const weatherConditions = {
    0: "NSW",
    4: "HZ",
    5: "FG",
    10: "BR",
    20: "REFG",
    21: "RE VCSH",
    22: "RE SHRA",
    23: "RERA",
    24: "RESN",
    25: "RE FZRA",
    30: "FG",
    31: "BCFG",
    32: "MIFG",
    33: "FG",
    34: "HVY FG",
    40: "RA",
    41: "FBL RA",
    42: "HVY RA",
    50: "DZ",
    51: "FBL DZ",
    52: "DZ",
    53: "HVY DZ",
    54: "FBL FZDZ",
    55: "FZDZ",
    56: "HVY FZDZ",
    60: "FBL RA",
    61: "FBL RA",
    62: "MOD RA",
    63: "HVY RA",
    64: "FBL FZRA",
    65: "FZDZ",
    66: "HVY FZDZ",
    67: "FBL SNRA",
    68: "SNRA",
    70: "SN",
    71: "FBL SN",
    72: "SN",
    73: "HVY SN",
    74: "FBL GS",
    75: "GS",
    76: "HVY GS",
    77: "SG",
    78: "PL",
    80: "SHRA",
    81: "FBL SHRA",
    82: "SHRA",
    83: "HVY SHRA",
    84: "HVY SHRA",
    85: "FBL SHSN",
    86: "SHSN",
    87: "HVY SHSN",
    89: "SHGR"
  };